-Areas, perimetros de triangulos equilatero

-Recibe una lista de 16 elementos, la transforme en una matriz de tamaño 4x4

-Funcion que calcule el determinante (np.linalg.det(a))

In [43]:
import numpy as np #se importan las funciones numpy

class Formula:
    def __init__(self, lado, lista):  #Se inicializa el programa con las variables, es la clase madre
        self.lado = lado
        self.lista = lista

class Determinant(Formula): #clase heredada
    def lista_matriz(self):

        matriz = np.array(self.lista).reshape(4, 4) #se hace una matriz 4x4
        determinante = np.linalg.det(matriz) #se calcula el determinante con funcion de la biblioteca numpy
        print("Matriz:")
        print(matriz)
        print("Determinante:", determinante)

lista = [6, 8, 3, 4, 9, 6, 7, 8, 9, 10, 8, 7, 8, 46, 15, 16]

class AreaPerimetro(Formula): #clase heredada
    def __init__(self, lado):
        super().__init__(lado, None) #Se utiliza las variables anteriores y el valor lista se considera nulo porque no se ocupa

    def perimetro(self): #Se crean polimorfismos de permitro
        perimetro = 3 * self.lado
        print("Perímetro:", perimetro)

    def area(self): #Se crea otro polimorfismo de area
        area = (self.lado**2 * np.sqrt(3)) / 4
        print("Área:", area)

side = float(input("Introduce la longitud del lado: ")) #se pide introduzir el lado

# se calcula el determinante
det = Determinant(side, lista)
det.lista_matriz()

# se calcula el perimetro
calculadora = AreaPerimetro(side)

# Se pide el valor de la calculador
calculadora.perimetro()
calculadora.area()

Introduce la longitud del lado: 5
Matriz:
[[ 6  8  3  4]
 [ 9  6  7  8]
 [ 9 10  8  7]
 [ 8 46 15 16]]
Determinante: -1846.0000000000011
Perímetro: 15.0
Área: 10.825317547305483
